version: '3'

services:
  afk_processing_container:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      network: host
      args: 
        BUILD_TYPE: "CUDA"
        VARIANT: 3.9
        NODE_VERSION: "lts/*"
    shm_size: '8G'
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/afk_image_processing:cached
      # - ${HOME}/projects/archmage-bot:/workspace/archmage-bot:cached
      - ${HOME}/projects/albedo-bot:/workspace/albedo-bot:cached
      - ${HOME}/.ssh:/home/vscode/.ssh
      # - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker

    # environment:
    #     SSH_AUTH_SOCK: /ssh-agent
    networks:
      - devnet
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  # redis:
  #   build:
  #     context: ./redis
  #     dockerfile: Dockerfile
  #     network: host
  #   command: redis-server
  #   networks:
  #     devnet:
  #       ipv4_address: 172.20.0.6
  #   ports:
  #    - "6379:6379"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    networks:
      devnet:
        ipv4_address: 172.40.0.7

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  devnet:
    ipam:
      # driver: default
      config:
        - subnet: 172.40.0.0/24
